#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Fri Sep 13 11:42:40 IST 2019
apiSecret=c49739fc7d8fcbdd04b9ac3768b5b351ba23a481dce95b8ab3939dc646ef12fd
